### ISSUE TITLE
HTTP request failed error on production server

### ISSUE THREAD

**Issue by avg0043** [guzzle/guzzle#2054]
Hi,

I'm running PHP 7 on my local testing server on Ubuntu 16.04 and all of my Guzzle http requests works perfectly. Problems comes when I use this library on my production server (Debian 9). I'm getting the following error from fopen() function:

```
 [GuzzleHttp\Exception\RequestException]                                                                                        
  Error creating resource: [message] fopen(http://my-url.com): failed to open stream: HTTP request failed!   
  [file] /var/www/api-producto/www/vendor/guzzlehttp/guzzle/src/Handler/StreamHandler.php                                        
  [line] 324 
```
Line 324 from `StreamHandler` class corresponds with : 

`$resource = fopen((string) $uri, 'r', null, $context);`

It seems that fopen() is failing the HTTP request in production environment but success on local environment. It's really strange because I'm using the same PHP code and request URL in both cases.
I think it should be some configuration of fopen(), PHP or Debian, but I not sure :S 

What can I do to solve this problem?
Thanks.

**Comment by hickmanjos** [comment]
Was this ever solved? Having something along the same lines of an issue.

**Comment by hickmanjos** [comment]
Adding to this, I fixed my issue by adding a timeout option to the guzzle request.

`
$options['timeout'] = 300;
$response = $client->request('POST', $url, $options);
`

**Comment by aunhappy** [comment]
same issue,did u solve it?

**Comment by hickmanjos** [comment]
> same issue,did u solve it?

My second comment is what I added my my guzzle request to get them to stop failing

**Comment by jbelien** [comment]
I ran into the same issue today.
I simply forgot to install/enable PHP curl extension ! 🤦‍♂️ 

On Ubuntu/Debian for PHP 7.3 :
```shell
sudo apt-get install php7.3-curl
```

**Comment by mikoop79** [comment]
if you are trying to hit a domain that is not accessible from the server eg a local domain. you need to add it to the hosts file on that server. 

`/etc/hosts`

**Comment by briancalma** [comment]
> ```shell
> sudo apt-get install php7.4-curl
> ```

Ran in the same issues today on Ubuntu 20.04 
Fixed it using the command above :)

**Comment by tishad770** [comment]
I am still facing the same issue on Ubuntu 20.04 and php 7.4

sudo apt-get install php7.4-curl didnt solve my problem.

**Comment by Nyholm** [comment]
I’m closing this since it is not a bug in guzzle.
