### ISSUE TITLE
Memory leak with streams

### ISSUE THREAD

**Issue by curtisdf** [guzzle/guzzle#2555]
**Guzzle version(s) affected**: 6.5.2 and 7.0.0-beta.1  (Probably earlier versions too)
**PHP version**: 7.2.26 and 7.3.11-13
**cURL version**: 7.61.1, 7.64.0, 7.65.3, and 7.67.0

**Description**  
When using Guzzle's `stream` config option to read from a remote HTTP stream, Guzzle exhibits a substantial memory leak, starting after it has already downloaded 2.00 MB of the stream's contents.

The rate of memory leakage appears to grow in 1:1 proportion to rate of data being downloaded from the stream.

The leak occurs in the following environments I've tested with:
* Alpine Linux 3.8 (PHP 7.2.26 / cURL 7.61.1 / Guzzle 6.5.2)
* Alpine Linux 3.9 (PHP 7.2.26 / cURL 7.64.0 / Guzzle 6.5.2)
* Alpine Linux 3.10 (PHP 7.3.11 / cURL 7.66.0 / Guzzle 6.5.2)
* Alpine Linux 3.11 (PHP 7.3.13 / cURL 7.67.0 / Guzzle 6.5.2, *and* Guzzle 7.0.0-beta.1)
* Ubuntu Linux 19.10 (PHP 7.3.11 / cURL 7.65.3 / Guzzle 6.5.2)
* Mac OS 10.15 (Homebrew PHP 7.3.12 / cURL 7.67.0 / Guzzle 6.5.2, *and* Guzzle 7.0.0-beta.1)

It does NOT occur in the following environments:
* Alpine Linux 3.7 (PHP 7.1.33 / cURL 7.61.1 / Guzzle 6.5.2)
* Mac OS 10.15 (Apple factory-installed PHP 7.3.9 / cURL 7.64.1 / Guzzle 6.5.2, *or* Guzzle 7.0.0-beta.1)

With the exception of the OSX Homebrew install listed above, in all environments I'm using the native PHP which comes by default with that OS's package manager. These binaries are not customized by myself in any way, nor are any unofficial package channels being used.

The amount of memory consumed also jumps by 2.00 MB at two different intervals prior to when the leak starts.  It only happens twice, which is tolerable. But still, it's unexplained.  These jumps only occur in the environments which exhibit the leak. They don't occur in the two environments which don't exhibit the leak.

**How to reproduce**  
Run the following script (assuming Guzzle is already installed via Composer):
```
<?php
require_once __DIR__ . '/vendor/autoload.php';
$guzzle = new \GuzzleHttp\Client;
$stream = $guzzle->get(
    'https://kpbs.streamguys1.com/?ck=1579203064304', 
    ['stream' => true]
)->getBody();

$downloaded = 0;
while (!$stream->eof()) {
    $line = $stream->read(8192);

    $downloaded += strlen($line);

    $dl = number_format($downloaded/1048576, 2);
    $mem = number_format(memory_get_usage(true)/1048576, 2);
    echo date('g:i:s') . ", downloaded $dl MB, mem $mem MB\n";
}
```

The output of this script is very similar in every case when the leak is occurring.  Here's a sample from my aforementioned Mac OS Homebrew environment:
```
1:47:47, downloaded 0.01 MB, mem 2.00 MB
1:47:47, downloaded 0.02 MB, mem 2.00 MB
1:47:47, downloaded 0.02 MB, mem 2.00 MB
1:47:47, downloaded 0.03 MB, mem 2.00 MB
1:47:47, downloaded 0.04 MB, mem 2.00 MB
...
1:47:48, downloaded 0.16 MB, mem 2.00 MB
1:47:48, downloaded 0.17 MB, mem 2.00 MB
1:47:48, downloaded 0.18 MB, mem 2.00 MB
1:47:48, downloaded 0.19 MB, mem 4.00 MB
1:47:48, downloaded 0.20 MB, mem 4.00 MB
1:47:48, downloaded 0.20 MB, mem 4.00 MB
...
1:49:41, downloaded 1.97 MB, mem 4.00 MB
1:49:41, downloaded 1.98 MB, mem 4.00 MB
1:49:42, downloaded 1.98 MB, mem 4.00 MB
1:49:42, downloaded 1.99 MB, mem 4.00 MB
1:49:43, downloaded 2.00 MB, mem 6.00 MB
1:49:43, downloaded 2.01 MB, mem 6.02 MB
1:49:44, downloaded 2.02 MB, mem 6.02 MB
1:49:44, downloaded 2.02 MB, mem 6.03 MB
1:49:45, downloaded 2.03 MB, mem 6.04 MB
1:49:46, downloaded 2.04 MB, mem 6.04 MB
1:49:46, downloaded 2.05 MB, mem 6.05 MB
1:49:46, downloaded 2.05 MB, mem 6.06 MB
...
1:49:56, downloaded 2.20 MB, mem 6.21 MB
1:49:57, downloaded 2.21 MB, mem 6.21 MB
1:49:57, downloaded 2.22 MB, mem 6.22 MB
1:49:58, downloaded 2.23 MB, mem 6.23 MB
1:49:58, downloaded 2.23 MB, mem 6.24 MB
1:49:59, downloaded 2.24 MB, mem 6.25 MB
1:49:59, downloaded 2.25 MB, mem 6.25 MB
1:50:00, downloaded 2.26 MB, mem 6.26 MB
1:50:00, downloaded 2.27 MB, mem 6.27 MB
1:50:01, downloaded 2.27 MB, mem 6.28 MB
1:50:01, downloaded 2.28 MB, mem 6.29 MB

```

Note that this script is discarding the contents of what's being downloaded, so its memory usage should be constant over time.  In the two environment where the leak doesn't occur, memory usage remains at 2.00 MB the entire time the script is running.  But with the leak, it jumps first to 4.00 MB for awhile, and then to 6.00 right as the memory beings growing with every additional chunk of the stream that's downloaded.  

**Possible Solution**  

Is Guzzle auto-detecting PHP 7.2 and later and behaving differently than with 7.1 and below?  Or is it auto-detecting a function or some other language feature that was introduced in 7.2?

But I can't explain why OSX Catalina with its native PHP 7.3 binary works just fine.  But every other combination of OS with PHP >= 7.2 and Guzzle >= 6.5 exhibits the leak.

**Additional context**  

The leak does not appear to depend on the content type of the stream.  My main use case is Twitter's GNIP PowerTrack stream, which is plain text.  But since that's behind an auth mechanism I can't share the details, so my test script above is using the publicly available KBPS stream from www.npr.org, which is an MPEG stream. The leak occurs with both streams.

The leak also doesn't seem to be affected by the number of bytes requested per chunk in the call to `$stream->read()`.  I also tried inputting values of `256` and `1024` but with no change in behavior.

**Comment by Nyholm** [comment]
Thank you. This is a great issue. If everybody wrote issues like this with reproducible code, maintaining open source would be super easy. 

I ran your script in Blackfire. Here is the profile: https://blackfire.io/profiles/c894c5c4-4a3b-4720-86a7-35a821c94c36/graph

My output looks like: 
```
7:11:19, downloaded 0.01 MB, mem 2.00 MB
7:11:19, downloaded 0.02 MB, mem 2.00 MB
...
7:11:20, downloaded 0.13 MB, mem 2.00 MB
7:11:20, downloaded 0.13 MB, mem 4.00 MB
...
7:13:14, downloaded 1.99 MB, mem 4.00 MB
7:13:14, downloaded 2.00 MB, mem 6.00 MB
...
7:13:54, downloaded 2.61 MB, mem 6.61 MB
7:13:55, downloaded 2.62 MB, mem 6.62 MB
...
7:14:33, downloaded 3.20 MB, mem 7.20 MB
7:14:33, downloaded 3.20 MB, mem 7.21 MB
...
7:16:29, downloaded 4.96 MB, mem 8.96 MB
7:16:29, downloaded 4.97 MB, mem 8.97 MB
...
7:17:36, downloaded 5.98 MB, mem 9.99 MB
7:17:36, downloaded 5.99 MB, mem 10.00 MB
7:17:37, downloaded 6.00 MB, mem 10.01 MB
```

One can see from the timeline that memory increase all the time. 

![Screenshot 2020-01-17 at 20 25 32](https://user-images.githubusercontent.com/1275206/72640156-91473880-3967-11ea-8bde-9956ab4ff339.png)

Looking at the memory profile, I can see that all memory consumption comes from `fread`. 
Just to be sure that Guzzle did not leak memory, I change the script to:

```php
<?php
require_once __DIR__ . '/vendor/autoload.php';
$guzzle = new \GuzzleHttp\Client;
$stream = $guzzle->get(
    'https://kpbs.streamguys1.com/?ck=1579203064304',
    ['stream' => true]
)->getBody();

$downloaded = 0;
$phpStream = $stream->detach();
unset($stream);
unset($guzzle);

while (!feof($phpStream)) {
    $line = fread($phpStream, 8192);
    $downloaded += strlen($line);

    $dl = number_format($downloaded/1048576, 2);
    $mem = number_format(memory_get_usage(true)/1048576, 2);
    echo date('g:i:s') . ", downloaded $dl MB, mem $mem MB\n";
}
```

As you can see, I `unset` both `$guzzle` and `$stream`. The `$phpStream` is a normal resource. 

I think you've found a memory leak in PHP.

**Comment by curtisdf** [comment]
Awesome, thanks for the additional testing. I'm not familiar with Blackfire. Looks like a really helpful tool. I'll have to look into it.

Yes, those memory usage charts are troubling to say the least.  😩 I did manage to come up with an alternate implementation for consuming my stream, which avoids Guzzle (well, `fread()` I guess) and uses plain cURL and stream wrappers, and it successfully avoids the leak.  When I get a bit more time, I want to do a little more testing before referring this issue to the PHP core dev team.

**Comment by Nyholm** [comment]
If/when you report the bug. Make sure to have a script with no guzzle and as little code as possible.

**Comment by kkopachev** [comment]
php-only reproduction script
```php

$downloaded = 0;

$context = stream_context_create([
    'http' => [
        'protocol_version' => '1.1',
    ],
]);

$stream = fopen('https://kpbs.streamguys1.com/?ck=1579203064304', 'r', null, $context);

while (!feof($stream)) {
    $line = fread($stream, 8192);
    $downloaded += strlen($line);

    $dl = number_format($downloaded / 1048576, 2);
    $mem = number_format(memory_get_usage(true) / 1048576, 2);
    echo date('g:i:s') . ", downloaded $dl MB, mem $mem MB\n";
}
```

Looks like setting `'protocol_version' => '1.0'` fixes the issue.

**Comment by curtisdf** [comment]
@kkopachev Thanks so much.  This provides a workaround for Guzzle in the meantime. I have verified that adding `version => 1.0` to the input options for the call to `\GuzzleHttp\Client::get()` avoids the leak.

I have submitted the following PHP core bug report: https://bugs.php.net/bug.php?id=79143

**Comment by boesing** [comment]
> I have submitted the following PHP core bug report: https://bugs.php.net/bug.php?id=79143

Voted on it already. 👍

**Comment by curtisdf** [comment]
Update: The bug is [fixed in PHP core](http://git.php.net/?p=php-src.git;a=commit;h=67421a780d670ea2eec8157c39f2682bb3cfb7dd), as of several hours ago. I suppose this means the next stable PHP release after today's date will include it.  Thanks everyone!

**Comment by Nyholm** [comment]
Great job @curtisdf!
PHP is a little bit better thanks to you.

**Comment by shubaivan** [comment]
```

**Comment by lifeofguenter** [comment]
I am still having this issue with latest 7.4/7.3/7.2 🤔

**Comment by blackandred** [comment]
I also have the issue on the Guzzle 7.3.0 and PHP 7.4/8.0
I'm debugging it for ~7 days, with no luck. 

The upgrade of PHP 7.4 reduced memory usage from 2 GB to 1 GB - I had old version of PHP 7.4, now I'm using latest and latest 8.0

But still - I'm just having a upload -> temporary file -> flysystem strem from temporary file -> min.io / google cloud (both behaves similar)

![image](https://user-images.githubusercontent.com/22807686/113248615-9b7bfb00-92bd-11eb-8899-7f2009b60c52.png)

**Comment by blackandred** [comment]
Edit: For me the issue is resolved on Guzzle 7.3 and PHP 8.0 currently. I possibly misunderstand the PHP's profiler data.
My docker contanier memory was growing and not freeing memory. I made a test - I wrote a CLI script to upload the data, the RAM memory was not freed in docker container - so I assumed that the RAM cache is counted. When I limit my docker container to eg. 500 mb ram, then the usage was ~300 mb instead of 2 GB when I gave 15 GB ram. At the last stage I profiled memory with `mprof` and it was... 30 mb :wink: 

So for documentation, in case somebody would have same issue - possibly the http://git.php.net/?p=php-src.git;a=commit;h=67421a780d670ea2eec8157c39f2682bb3cfb7dd resolved the issue, and later it was just a false alarm. Before that fix I really had 2 GB usage and had to increase memory_limit to debug it.

**Comment by damian-keska-f** [comment]
That indeed looks misleading in docker https://github.com/moby/moby/issues/10824

**Comment by khanakia** [comment]
There is still an issue memory keeps increasing when i use `$body = $response->getDecodedBody();` the memory starts increasing i tried unsetting the client, response, body etc.

```php
for {
  $response = $client->get(
      path: $path,
      query: $query
    );
  
  $body = $response->getDecodedBody();
}
```
## Memory ussage with each loop
40.5 mb
58.5 mb
60.5 mb
62.5 mb
64.5 mb
