### ISSUE TITLE
guzzle get large body curl error

### ISSUE THREAD

**Issue by SugarShen** [guzzle/guzzle#2973]
**Guzzle version(s) affected**: 6.5.5
**PHP version**: 7.2.31
**cURL version**: 7.61.1

**Description**  
guzzle works fine util get a large body(4M).

my code 
```
<?php
require_once __DIR__.'/../vendor/autoload.php';

use GuzzleHttp\Client;
use GuzzleHttp\Exception\RequestException;


$client = new Client([
    'timeout'  => 5,
]);

try {
    $response = $client->request('GET', 'https://xxx/tmp.txt');
} catch (RequestException $e) {
    echo $e->getMessage();
}
```
 This code runs in php-cli is ok.  
`php tmp.php`
runs in php-fpm mode produces curl error.
The error:
`cURL error 23: Failed writing body (563 != 16384)`
I tried to check the permissions, nginx and php-fpm run as root, but error still produce.
please help me T-T.

**Comment by GrahamCampbell** [comment]
Guzzle 6.5.5 is no longer supported, sorry. Please upgrade to 7.4.1. A quick Google tells me this is probably resolved by upgrading to the latest libcurl and PHP (and Guzzle).

**Comment by SugarShen** [comment]
> Guzzle 6.5.5 is no longer supported, sorry. Please upgrade to 7.4.1. A quick Google tells me this is probably resolved by upgrading to the latest libcurl and PHP (and Guzzle).

guzzle upgrade to 7.4.1. php upgrade to 7.4.23. but error still produce.

**Comment by GrahamCampbell** [comment]
Are you still linked against an old version of libcurl?

**Comment by SugarShen** [comment]
> Are you still linked against an old version of libcurl?

thanks for your help guy. my mistake.
Setting  tmp dir  in php-fpm.conf  is not exist. 
I'm sorry. thx again
